#!/bin/bash

function print_help() {
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "  -help Print this help message and exit."
  echo "  -install Install sycl examples."
  echo "  -run <example> Run the example."
  echo "  -format Format the source code with clang-format."
  echo "  -format-check Check if source formatting is compliant with clang-format."
  echo "  -tidy Run clang-tidy."
}

if [[ $# -eq 0 ]]; then
  print_help
  exit 1
fi

SYCL_TRAIN_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYCL_TRAIN_STATE_PATH="${SYCL_TRAIN_SOURCE_DIR}/.9_sycl_of_hell_state"

# Set default values.
: ${SYCL_TRAIN_FORMAT:=NO}
: ${SYCL_TRAIN_FORMAT_CHECK:=NO}
: ${SYCL_TRAIN_TIDY:=NO}
: ${SYCL_TRAIN_INSTALL:=NO}
: ${SYCL_TRAIN_RUN:=NO}
: ${SYCL_TRAIN_RUN_ALL:=NO}
: ${SYCL_TRAIN_RUN_EXAMPLE:=}

# Read state variables created by `configure`.
if [[ -f "${SYCL_TRAIN_STATE_PATH}" ]]; then
  source "${SYCL_TRAIN_STATE_PATH}"
else
  echo "Error: You should run ./cmake-configure before running ${0}."
  exit 1
fi

# Handle command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -help)
      print_help
      exit 0
      ;;
    -format)
      SYCL_TRAIN_FORMAT="YES"
      shift
      ;;
    -format-check)
      SYCL_TRAIN_FORMAT_CHECK="YES"
      shift
      ;;
    -tidy)
      SYCL_TRAIN_TIDY="YES"
      shift
      ;;
    -install)
      SYCL_TRAIN_INSTALL="YES"
      shift
      ;;
    -run)
      SYCL_TRAIN_RUN="YES"
      SYCL_TRAIN_RUN_EXAMPLE=$2
      shift
      shift
      ;;
    -run_all)
      SYCL_TRAIN_RUN_ALL="YES"
      shift
      ;;
    *)
      echo "Unknown option: $1"
      print_help
      exit 1
      ;;
  esac
done

err=0

if [[ "${SYCL_TRAIN_FORMAT}" == "YES" ]]; then
  cmake --build ${SYCL_TRAIN_BUILD_DIR} --target format --parallel 4
  err=$(( $err + $? ))
fi

if [[ "${SYCL_TRAIN_FORMAT_CHECK}" == "YES" ]]; then
  cmake --build ${SYCL_TRAIN_BUILD_DIR} --target format-check --parallel 4
  err=$(( $err + $? ))
fi

if [[ "${SYCL_TRAIN_TIDY}" == "YES" ]]; then
  cmake --build ${SYCL_TRAIN_BUILD_DIR} --target tidy --parallel 4
  err=$(( $err + $? ))
fi

if [[ "${SYCL_TRAIN_INSTALL}" == "YES" ]]; then
  cmake --build ${SYCL_TRAIN_BUILD_DIR} --target install --parallel 4
  err=$(( $err + $? ))
fi

if [[ "${SYCL_TRAIN_RUN}" == "YES" ]]; then
  example=${SYCL_TRAIN_INSTALL_PREFIX}/bin/${SYCL_TRAIN_RUN_EXAMPLE}
  if [ ! -f ${example} ]; then
    echo "The example \"$SYCL_TRAIN_RUN_EXAMPLE\" is either invalid or not yet installed."
    exit 1
  fi
  $example
  err=$(( $err + $? ))
fi

if [[ "${SYCL_TRAIN_RUN_ALL}" == "YES" ]]; then
  for example in `ls ${SYCL_TRAIN_INSTALL_PREFIX}/bin/*`; do
    echo "Running example: ${example}"
    $example
    err=$(( $err + $? ))
  done
fi

exit $err
