#!/bin/bash

function print_help() {
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "  -help Print this help message and exit."
  echo "  -cxx <compiler> Set the compiler to be used for the build."
  echo "  -cxxflags <compiler flags> Set compiler flags to use for the build."
  echo "  -build-type <Release|RelWithDebInfo|Debug> Build type."
  echo "  -build-dir <build directory> Build directory."
  echo "  -install-prefix <install prefix> Install prefix."
  echo "  -enable-asan Enable address sanitizer."
}

SYCL_TRAIN_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYCL_TRAIN_STATE_PATH="${SYCL_TRAIN_SOURCE_DIR}/.9_sycl_of_hell_state"

# Set default values.
: ${SYCL_TRAIN_CXX:="icpx"}
: ${SYCL_TRAIN_CXX_FLAGS:="-O2"}
: ${SYCL_TRAIN_BUILD_TYPE:=RelWithDebInfo}
: ${SYCL_TRAIN_BUILD_DIR:=`pwd`/build}
: ${SYCL_TRAIN_INSTALL_PREFIX:=`pwd`/install}
: ${SYCL_TRAIN_ENABLE_ASAN:=OFF}

# Handle command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -help)
      print_help
      exit 0
      ;;
    -cxx)
      SYCL_TRAIN_CXX="$2"
      shift
      shift
      ;;
    -cxxflags)
      SYCL_TRAIN_CXX_FLAGS="$2"
      shift
      shift
      ;;
    -build-type)
      SYCL_TRAIN_BUILD_TYPE="$2"
      shift
      shift
      ;;
    -build-dir)
      SYCL_TRAIN_BUILD_DIR="$2"
      shift
      shift
      ;;
    -install-prefix)
      SYCL_TRAIN_INSTALL_PREFIX="$2"
      shift
      shift
      ;;
    -enable-asan)
      SYCL_TRAIN_ENABLE_ASAN="ON"
      shift
      ;;
    *)
      echo "Unknown option: $1"
      print_help
      exit 1
      ;;
  esac
done

mkdir -p ${SYCL_TRAIN_BUILD_DIR} 2> /dev/null

cmake -B ${SYCL_TRAIN_BUILD_DIR} -S . \
  -DCMAKE_CXX_COMPILER=${SYCL_TRAIN_CXX} \
  -DCMAKE_CXX_FLAGS="${SYCL_TRAIN_CXX_FLAGS}" \
  -DCMAKE_BUILD_TYPE=${SYCL_TRAIN_BUILD_TYPE} \
  -DCMAKE_INSTALL_PREFIX=${SYCL_TRAIN_INSTALL_PREFIX} \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DENABLE_ASAN=${SYCL_TRAIN_ENABLE_ASAN}

# Update variables required by the `9_sycl_of_hell` script.
echo "SYCL_TRAIN_BUILD_DIR=${SYCL_TRAIN_BUILD_DIR}" >> ${SYCL_TRAIN_STATE_PATH}
