name: Build and run 9_sycl_of_hell examples

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: true

jobs:
  run:
    strategy:
      matrix:
        include:
          - name: "[Ubuntu] Intel/LLVM"
            os: ubuntu-latest
            use_cmake: false
          - name: "[Ubuntu] CMake + Intel/LLVM"
            os: ubuntu-latest
            use_cmake: true

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3.13
      if: ${{ inputs.debug_enabled }}

    - name: add oneAPI to apt
      shell: bash
      run: |
        cd /tmp
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
      
    - name: install Intel oneAPI dpcpp compiler
      shell: bash
      run: |
        sudo apt update
        sudo apt install intel-oneapi-compiler-dpcpp-cpp

    - name: Set oneAPI environment variables
      shell: bash
      run: |
        echo "export ONEAPI_DEVICE_SELECTOR=opencl:cpu" >> ${GITHUB_ENV}

    - name: CMake configure
      if: ${{ matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./configure-cmake

    - name: CMake build
      if: ${{ matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        ./9_sycl_of_hell -install

    - name: Run CMake examples
      if: ${{ matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        source /opt/intel/oneapi/setvars.sh

        ./9_sycl_of_hell -run_all

    - name: Make build
      if: ${{ !matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        source /opt/intel/oneapi/setvars.sh
        CXX=icpx make -j 4

    - name: Run Make examples
      if: ${{ !matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        source /opt/intel/oneapi/setvars.sh

        make run_all

    - name: Block to allow inspecting failures
      run: sleep 1800
      if: ${{ failure() && inputs.debug_enabled }}
