name: Build and run 9_sycl_of_hell examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: true

jobs:
  run:
    strategy:
      matrix:
        include:
          - name: "[Ubuntu] Intel/LLVM"
            os: ubuntu-latest
            use_cmake: false
          - name: "[Ubuntu] CMake + Intel/LLVM"
            os: ubuntu-latest
            use_cmake: true

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3.13
      if: ${{ inputs.debug_enabled }}

    - name: add oneAPI to apt
      shell: bash
      run: |
        cd /tmp
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"

    - name: install Intel oneAPI dpcpp compiler
      shell: bash
      run: |
        sudo apt update
        sudo apt install intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mkl-devel

    - name: Set oneAPI environment variables
      shell: bash
      run: |
        echo "export ONEAPI_DEVICE_SELECTOR=opencl:cpu" >> ${GITHUB_ENV}

    - name: CMake
      if: ${{ matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./configure-cmake
        ./9_sycl_of_hell -install
        ./9_sycl_of_hell -run_all

    - name: Make 9_sycl_of_hell
      if: ${{ !matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        source /opt/intel/oneapi/setvars.sh
        CXX=icpx make -j 4
        make run_all

    - name: Make advanced_inferno/
      if: ${{ !matrix.use_cmake }}
      working-directory: advanced_inferno
      run: |
        source /opt/intel/oneapi/setvars.sh
        CXX=icpx make -j 4
        make run_all

    - name: Block to allow inspecting failures
      run: sleep 1800
      if: ${{ failure() && inputs.debug_enabled }}

  acpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install deps
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh 
        sudo bash ./llvm.sh 19  
        sudo apt install -y  libboost-fiber-dev libboost-context-dev
    - uses: actions/cache@v4
    - name: Cache acpp
      id: acpp
      with:
        path: ~/acpp/
        key: ${{ runner.os }}-build-cache-acpp
    - name: Install
      if: steps.acpp.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/AdaptiveCpp/AdaptiveCpp
        cd AdaptiveCpp
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/acpp -DLLVM_DIR=/usr/lib/llvm-19/cmake/ ..
        make install
    - name: Make 9_sycl_of_hell
      if: ${{ !matrix.use_cmake }}
      working-directory: 9_sycl_of_hell
      run: |
        CXX=$HOME/bin/acpp CXXFLAGS='-O2'  make -j 4
        make run_all

